showWin <- function(){
gplot(birdObj)
gplot(zoomObj)
gplot(scatterObj)
gplotIsland(r1,r2,id=1)
mywindow <<- Qt$QWidget()
mywindow$resize(1000,800)
layout <- Qt$QGridLayout()
mywindow$setLayout(layout)
layout$addWidget(view.bird,0,0,1,2)
layout$addWidget(v.scatter,1,0)
layout$addWidget(widgetZoom,0,2,2,1)
layout$addWidget(viewIsland,1,1)
layout$setRowStretch(0,1)
layout$setRowStretch(1,1)
layout$setColumnStretch(0,1)
layout$setColumnStretch(1,1)
layout$setColumnStretch(2,2)
mywindow$show()
}
